---
- name: Create steamcmd folder
  ansible.builtin.file:
    path: "{{ steamcmd_path }}"
    state: directory
    owner: "{{ srcds_username }}"
    mode: 'u=rwx,g=rwx,o=r'

- name: Download and extract steamcmd
  ansible.builtin.unarchive:
    src: http://media.steampowered.com/client/steamcmd_linux.tar.gz
    remote_src: true
    dest: "{{ steamcmd_path }}"
    owner: "{{ srcds_username }}"

- name: Fix permissions
  ansible.builtin.file:
    path: "{{ steamcmd_path }}"
    owner: "{{ srcds_username }}"
