---
- name: Create server directory
  file:
    path: "{{ srcds_server_path }}"
    state: directory
  become: true
  become_user: "{{ srcds_username }}"

- name: Download srcds server
  command: "{{ steamcmd_path }}/steamcmd.sh +login anonymous +force_install_dir {{ srcds_server_path }} +app_update {{ srcds_gameid }} +quit"
  become: true
  async: 3600
  poll: 30
  become_user: "{{ srcds_username }}"

- name: Copy default server.cfg
  template:
    src: server.cfg
    dest: "{{ srcds_server_path }}/tf/cfg/server.cfg"
    owner: "{{srcds_username}}"