name: Pipeline

on: 
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main

jobs:
  validate_terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    container: sonikro/terragrunt-ansible:1.2.4-5.8.0
    steps:
    - name: Check out code  
      uses: actions/checkout@v2

    - name: Validate
      shell: sh
      run: |
        terraform init -backend=false
        terraform fmt -check
        terraform validate

  validate_ansible:
    name: Validate Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Ansible Lint
        uses: ansible-community/ansible-lint-action@v6.2.1
        with:
          path: "ansible/"
